### PR TITLE
Align the short and long forms into their own columns in the help output

### PR DESCRIPTION
**Pull request by akhoury6**
This makes displaying a mixed set of parameters cleaner and easier to understand. This is in line with the behavior of common GNU tools such as rsync.

Old way:
```
Options:
  -i, --init        Creates a skeleton config file in the current working directory
  -v, --verbose     Enables verbose output. Twice will enable very-verbose output (good for logging)
  -y, --yes         Assume 'yes' to all questions for headless execution
  --yaml=<s>        Specify a yaml file to load
  -h, --help        Show this message
```

New way:
```
Options:
  -i, --init        Creates a skeleton config file in the current working directory
  -v, --verbose     Enables verbose output. Twice will enable very-verbose output (good for logging)
  -y, --yes         Assume 'yes' to all questions for headless execution
      --yaml=<s>    Specify a yaml file to load
  -h, --help        Show this message
```

### CODE REVIEW

**Comment by akhoury6** [comment]
Sorry guys, just a few minutes and I'll have the tests sorted out. Slipped by me.

**Comment by akhoury6** [comment]
Done. The remaining tests that are failing seem to be for unrelated issues.

**Comment by Fryguy** [comment]
If there are only long forms, is the whole output kind of indented?

**Comment by akhoury6** [comment]
I can't seem to test that in the real world as there's always a line that says `-h, --help       Show this message`. Unless you can make that line go away I think that situation would never arise.

**Comment by Fryguy** [comment]
Yeah you're right, at least not without some hackery.  A user can override the message for help, and they can override the short form of help, but they can't _remove_ the short form.

**Review by Fryguy — APPROVED** [review]

**Pull request merged**
