### PR TITLE
Refactor constraints

### LINKED ISSUE #131: Add general constraint handling that can be the basis of depends/conflicts/either
From https://github.com/ManageIQ/optimist/pull/130#issuecomment-1100475979, @nanobowers wrote:
> This seems like a specialization of a more general type of argument validation.
> 
> More specifically, the condition you are trying to satisfy with either: is max==1 and min==1. Should we entertain cases where min/max are not 1? conflicts: is kinda like max==1 and min==ANY
> 
> Was thinking something along the lines of:
> 
> ```ruby
> validate min: <Integer/nil>, max: <Integer/nil>, args: <Array of Symbol>
> ```

### PR DESCRIPTION
**Pull request by nanobowers**
+ Refactor constraints (depends/conflicts/either) into separate classes (`DependConstraint`, `ConflictConstraint`, `EitherConstraint`) with an abstract `Constraint` class.
+ ~Add `validate` method which points to new `MinMaxConstraint`, plus tests.~
   + ~tbh i'm not too sure about the `validate` name, the name feels a little unclear about its purpose to me.~

@miq-bot add-label refactoring
@miq-bot add-reviewer @Fryguy

### CODE REVIEW

**Comment by nanobowers** [comment]
Realized I did not update the documentation, but would like to get feedback on this so moving to draft

**Comment by Fryguy** [comment]
> tbh i'm not too sure about the validate name, the name feels a little unclear about its purpose to me.

This was also my only concern here.  It also takes away from what might be other use cases for validation.  For example, we might want to allow similar things to what activerecord validation provides, such as :format or :comparison.  That is I could see something like:

```
opt :max_volume, :type => :integer
opt :start_volume, :type => :integer
validates :start_volume, comparison: { less_than_or_equal_to: :max_volume }
```

---

So I think the way forward is give a more clear name for the minmax, but that will likely hold up the refactoring.  I'd be ok with a separate PR with just the refactorting, since that's much clearer and I'm basically ready to merge now, and then the mixmax bit can be a smaller PR.  I'm still not sure of a realistic use case is for mix max, which makes it a little harder for me to understand.

**Comment by nanobowers** [comment]
Reverted this to a plain old refactoring of the depend/conflict/either constraints.  Can tackle min/max validation in another PR.

**Review by Fryguy — APPROVED** [review]

**Comment by Fryguy** [comment]
I'm surprised that no specs failed with the changes in wording.  Are these tested?

**Comment by nanobowers** [comment]
> I'm surprised that no specs failed with the changes in wording. Are these tested?

No, apparently not.  The difference in the algorithm for determining success/failure of the Constraints would make it impractical to match the old failure messages.

Should I put together some tests for the failure messages before closing out this PR?

**Comment by Fryguy** [comment]
> Should I put together some tests for the failure messages before closing out this PR?

Yes, please - even a few basic tests would be sufficient.

**Pull request merged**
